### ISSUE TITLE
Don't work with Expo 23

### ISSUE THREAD

**Issue by kornacki** [expo/videoplayer#11]
`Invalid Version: undefined`

warning " > @expo/videoplayer@0.1.13" has incorrect peer dependency "expo@^22.0.0".

**Comment by davidcantonnoteges** [comment]
Some news for this issue?

**Comment by pavle93** [comment]
Is there a workaround ?

**Comment by eliysha** [comment]
+1

**Comment by hardcodet** [comment]
@pavle93 Dirty hack for now is to just remove/adjust the peer dependency in the package.json at `@expo/videoplayer`.

**Comment by abi** [comment]
Fixed in 0.3.0

**Comment by abi** [comment]
Sorry for the delay, y'all!
