### ISSUE TITLE
Don't work with Expo 24

### ISSUE THREAD

**Issue by Adherentman** [expo/videoplayer#13]
`Invalid Version: undefined`

That's means I have to use Exop 22?

**Comment by Adherentman** [comment]
@abi Hello,Could you update expo?

**Comment by abi** [comment]
Will update!

**Comment by Adherentman** [comment]
@abi Thanks!:)

**Comment by nyenye** [comment]
Is it already solved? I've had the same issue just today...

**Comment by abi** [comment]
Fixed in 0.3.0
